# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
    nightly:
      rustup_toolchain: nightly

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: rustup target add thumbv7em-none-eabihf
    displayName: Add ARM target
  - script: cargo build --verbose --all --target=thumbv7em-none-eabihf
    displayName: Cargo build
  - script: cargo test --verbose --all
    displayName: Cargo test